import "~/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";

import type { PropsWithChildren } from "react";

import { Theme } from "@radix-ui/themes";

// import { NextUIProvider } from "@nextui-org/react";
import { ThemeProvider } from "./_components/theme-provider";
import { getServerAuthSession } from "~/server/auth";

import { Navbar } from "~/app/_components/navbar/navbar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({ children }: PropsWithChildren) {
  const session = await getServerAuthSession();

  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider>
          {/* <NextUIProvider> */}
          <ThemeProvider>
            <Theme radius="large">
              <Navbar session={session} />
              {children}
            </Theme>
          </ThemeProvider>
          {/* </NextUIProvider> */}
        </TRPCReactProvider>
      </body>
    </html>
  );
}
